# Generated by Django 5.0.2 on 2024-02-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=100)),
                ('start_from', models.CharField(max_length=50)),
                ('end_from', models.CharField(max_length=100)),
            ],
        ),
    ]
