# Generated by Django 5.0.2 on 2024-02-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('std_age', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='routes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolbus',
            name='id',
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolbus',
            name='bus_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
