# Generated by Django 5.0.2 on 2024-02-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_students_remove_routes_id_remove_schoolbus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbus',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolbus',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolbus',
            name='std_age',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolbus',
            name='std_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolbus',
            name='student_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
